### ISSUE TITLE
[1pt] modules with jupyter_packaging fails during pytest in prow because of setuptools in wrong version

### ISSUE THREAD

**Issue by pacospace** [thoth-station/zuul-test-infra#50]
**Is your feature request related to a problem? Please describe.**
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from jupyter_packaging import create_cmdclass, install_npm, ensure_targets, combine_commands
  File "/opt/app-root/lib64/python3.8/site-packages/jupyter_packaging/__init__.py", line 6, in <module>
    from .setupbase import *
  File "/opt/app-root/lib64/python3.8/site-packages/jupyter_packaging/setupbase.py", line 37, in <module>
    from setuptools.config import StaticModule
ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/opt/app-root/lib64/python3.8/site-packages/setuptools/config.py)
Aborting due to errexit on line 14. Exit code: 1
```

**Describe the solution you'd like**
Have image with "setuptools>=46.4.0"
See comment from Jupyter maintainers: https://githubmemory.com/repo/jupyter/notebook/issues/6056

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
from `quay.io/thoth-station/thoth-pytest-py38:v0.13.0` container 
```
(app-root) pip show setuptools
Name: setuptools
Version: 41.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /opt/app-root/lib/python3.8/site-packages
Requires: 
Required-by: thoth-python, thamos, kubernetes, jsonschema, google-auth
(app-root) 
```

**Comment by goern** [comment]
does this problem still exist with v0.14.3?

/kind bug
/priority critical-urgent
/remove-label kind/feature

**Comment by goern** [comment]
is this still relevant?
/priority important-soon
